### ISSUE TITLE
what is the caller of this script?

### ISSUE THREAD

**Issue by braindevices** [netbootxyz/build-pipelines#4]
I am completely disoriented. I try to understand how do you prepare the http bootable Live CD components. However there are so many separated repos are scattering around. I feel probably we should use submodule to handle it, if you really want to separate a single file into a repo.

There is `TYPE="$1" ARG="$2"`, so apparently depending on what args are giving to this script, the script will run different segment in this file. But what actually calling this script? I cannot find any build.sh word in netbot.xyz. There is also another build.sh in `ghcr.io/netbootxyz/iso-processor`.

In the `ghcr.io/netbootxyz/iso-processor` there is a `buildin` folder, where does it came from? It looks like in this repo's build.sh it rename buildout to buildin. But where is the first buildin came from? And there is a folder called `initrd_files`, I cannot find this word anywhere neither. Apparently this build.sh should be called several times in a sequence where is sequence defined?

**Comment by braindevices** [comment]
I guess this build.sh is called by `.travis.yml` in each squash repo. Maybe rename it to a more meaningful name since we have build.sh in squash repos already.?

**Comment by braindevices** [comment]
where is the `/modlayer/` came from?

**Comment by braindevices** [comment]
ok it comes from the docker itself https://github.com/netbootxyz/docker-mod-layers

**Comment by antonym** [comment]
We no longer use Travis and it's all Github Actions.  The build script is called via the Actions workflow in each branch of the Live CD component we are going to build.  If it needs additional modifications to make it more netbootable friendly, that branch will container a docker file which will pull down the mod layers, apply it to the live components and then upload the modified components as a release.

https://github.com/netbootxyz/ubuntu-squash/blob/ubuntu-mate-20.04/.github/workflows/ubuntu-mate-20.04.yml#L14

https://github.com/netbootxyz/ubuntu-squash/blob/ubuntu-mate-20.04/Dockerfile

**Comment by antonym** [comment]
This probably provides the best mapping of all of the active repos being built:

https://github.com/netbootxyz/pipeline-status/blob/main/README.md

**Comment by braindevices** [comment]
@antonym thanks a lot
